# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    build: ./mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./databases:/data/db

  mongo-express:
    build: ./mongo-express
    restart: always
    ports:
      - 6081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

  python3:
    build: ./python3
    restart: always
